### PR TITLE
Insert missing equal signs ("=") in example php.ini

### PR DESCRIPTION
**Pull request by lauritzh**
When setting up an DVWA instance I noticed the syntax error, thus I suggest this minor fix.

Cheers,
lauritzh

### CODE REVIEW

**Comment by digininja** [comment]
Is this file still used for anything?

**Comment by lauritzh** [comment]
Hi @digininja! Thanks for your fast reply :)

I deployed the sources on an more or less raw apache2 with php (dockerhub: php:apache), and its default config was to use the above mentioned php.ini. I'm not sure how common this scenario is, but I ran into this problem and to correct the syntax of your php.ini worked for me.

So as you imply one could either delete the file or correct the syntax. I would agree on both options. :man_shrugging: 

Cheers,
lauritzh

P.S.: I am aware of your Docker image, but intentionally chose to build my own image to be more flexible. Keep up the great work! :)

**Comment by digininja** [comment]
The fix looks good so let's just get it in and then worry about if the file
is actually needed later.

**Comment by digininja** [comment]
@ethicalhack3r nudge on this one

**Comment by ethicalhack3r** [comment]
Thanks!

**Pull request merged**
