### PR TITLE
Correct the MySql Setup Check to include both MySql and MySqli extens…

### PR DESCRIPTION
**Pull request by hanoncs**
…ions

This is a very small change to add support for MySql orMySqli extensions on the setup page.

I had php7 with mysqli extension installed and it was showing "Missing". Now it correctly displays "Installed".

I cannot test this on php5 with mysql extension. Please let me know if issues.

### CODE REVIEW

**Comment by hanoncs** [comment]
I changed it to only fix the mysqli typo.

**Comment by jehy** [comment]
That won't work with php using deprecated mysql extension.

**Comment by digininja** [comment]
It stopped using the deprecated MySQL functions a long time ago.

**Comment by hanoncs** [comment]
Hello, can this not be merged??

**Comment by ethicalhack3r** [comment]
Merged! Thank you!

**Comment by hanoncs** [comment]
No, thank you, this was my first ever oss contribution. Wish I could find more things to help with.

**Comment by ethicalhack3r** [comment]
Awesome!

There are plenty of things in DVWA that could do with looking at. Take a look through some of the issues posted by other users for some inspiration.

What would *really* be useful in my opinion is automated testing of DVWA's features using something like PHPUnit https://phpunit.de/

Automated testing would ensure features work the way they should and any future changes don't break them.

**Comment by digininja** [comment]
If you want something a bit smaller, have a look at the bug I talk about in
here:

https://github.com/ethicalhack3r/DVWA/issues/120

A fix would require decoupling phpids from the security level in some way.

**Comment by hanoncs** [comment]
Sounds good thanks. I'll take a look at the open issues. I have a little experience with PHPUnit. When I have time i'll see what I can do.

**Pull request merged**
