### PR TITLE
Added Weak Session ID vulnerability

### PR DESCRIPTION
**Pull request by digininja**

### CODE REVIEW

**Comment by ethicalhack3r** [comment]
Hey! Just checking if you've finished on this one and want me to merge?

**Comment by digininja** [comment]
as long as you are happy with it, it's ready to merge

**Comment by ethicalhack3r** [comment]
Did you add the httponly and samesite cookie flags? I can't seem to find them in the commits

**Comment by digininja** [comment]
I did, unless I forgot to push it, will check.

Just noticed the mysqli_ clean up broke some things, fixing them now

**Comment by digininja** [comment]
Added the flags again. Bloody hate git, learned how to do a merge with upstream and fix conflicts though, will have forgotten how to do it by the next time it is needed though.

**Pull request merged**
