### PR TITLE
correctly reference JS files

### PR DESCRIPTION
**Pull request by digininja**
When I wrote the module I assumed the files were located off the root, the fix in #340 assumes they are off /dvwa. This fixes it correctly and makes the path relative.

### CODE REVIEW

**Comment by digininja** [comment]
The gitignore is supposed to be a separate PR, but I can't use git very well do it's in here by accident.

**Comment by CousinOkri** [comment]
Yep. This fix is much better. My bad. Thanks for the update.

**Comment by digininja** [comment]
Thanks for spotting it in the first place. Hope you manage to solve the
problem now you've got the question working.

**Comment by CousinOkri** [comment]
Still trying to get through high. Will keep working on it, though!

**Comment by digininja** [comment]
@ethicalhack3r Nudge...

**Pull request merged**
