### PR TITLE
Update MySQL to MySQLi for work into php 7.0

### PR DESCRIPTION
**Pull request by GoldraK**
I Update all app, to work in php 7.0, change all mysqli and adapt the installer.

### CODE REVIEW

**Comment by ethicalhack3r** [comment]
Hi, it looks like you made your changes to an older version of DVWA?

Can you make your changes to the latest master branch and do another pull request please?

**Comment by GoldraK** [comment]
hello, I did in the last version 1.9 that had zipped, no difference with the repo?

**Comment by ethicalhack3r** [comment]
I don't know how you did it but it looks like you modified an older version, unless you deliberately changed things back to how they used to be which is unlikely. Can you explain this change? https://github.com/ethicalhack3r/DVWA/pull/98/commits/c787c1617ee3644b6a5b672d4715e1d2288f9c4c#diff-04c6e90faac2675aa89e2176d2eec7d8L120

**Comment by GoldraK** [comment]
that change the link I did not do was so down in the version and upload the differences found.

In the about only add me and change version 1.9 to 1.9.1

**Pull request closed without merging**
