### PR TITLE
Captcha fix

### PR DESCRIPTION
**Pull request by Exhibitioner**
Fix Google Recaptcha, upgraded to Recaptcha v2 (v1 will cease to exist > 31st March).

As far as I can tell it is working, though let me know if any issues.

### CODE REVIEW

**Comment by digininja** [comment]
I've not checked it yet but some comments...

Remove the .bak file, it shouldn't be there

Do the levels still function as expected? Can you bypass low without any
effort? Is medium then hard getting harder and is impossible, impossible?

**Comment by Exhibitioner** [comment]
Yup, functionality seems unchanged for me. Was able to bypass the 3 stages.

**Comment by ethicalhack3r** [comment]
Had a quick look over the changes. They look good to me.

@mike-bailey @digininja let me know if you're happy for me to merge.

**Comment by digininja** [comment]
Line 22 of high.php, I think the logic is wrong and was before this fix. The way it is, if resp == false then you will always get the error message, despite doing the hacky stuff to avoid it as it is (!$resp && xxx).

Can I propose this instead which I think is easier to read and is possible to bypass by setting the user agent and the string.

```
    if( $resp || ( $_POST[ 'g-recaptcha-response' ] == 'hidd3n_valu3' && $_SERVER[ 'HTTP_USER_AGENT' ] == 'reCAPTCHA' ) ) { 
        // CAPTCHA was correct. Do both new passwords match?
        if( $pass_new == $pass_conf ) { 
            $pass_new = ((isset($GLOBALS["___mysqli_ston"]) && is_object($GLOBALS["___mysqli_ston"])) ? mysqli_real_escape_string($GLOBALS["___mysqli_ston"],  $pass_new ) : ((trigger_error("[MySQLConverterToo] Fix the mysql_escape_string() call! This code does not work.", E_USER_ERROR)) ? "" : "")); 
            $pass_new = md5( $pass_new );

            // Update database
            $insert = "UPDATE `users` SET password = '$pass_new' WHERE user = '" . dvwaCurrentUser() . "' LIMIT 1;";
            $result = mysqli_query($GLOBALS["___mysqli_ston"],  $insert ) or die( '<pre>' . ((is_object($GLOBALS["___mysqli_ston"])) ? mysqli_error($GLOBALS["___mysqli_ston"]) : (($___mysqli_res = mysqli_connect_error()) ? $___mysqli_res : false)) . '</pre>' );

            // Feedback for user
            $html .= "<pre>Password Changed.</pre>";
        }   
        else {
            // Ops. Password mismatch
            $html     .= "<pre>Both passwords must match.</pre>";
            $hide_form = false;
        }   
    } else {
        // What happens when the CAPTCHA was entered incorrectly
        $html     .= "<pre><br />The CAPTCHA was incorrect. Please try again.</pre>";
        $hide_form = false;
        return;
    }   
```

**Comment by Exhibitioner** [comment]
I too thought the logic on the high one was a little odd, I believe I bypassed that by setting the hidden value and the user agent if I remember correctly?

Suggested fix definitely seems better IMO, let me know if you want me to go and update that too

**Comment by digininja** [comment]
I hate boolean logic so it may have worked, I was trying to test it with
firefox inspector pane. Make the update if you agree that it looks better,
I think it makes more sense.

**Comment by ethicalhack3r** [comment]
Hey! Am I OK to merge, or would you like me to wait? Thanks!

**Comment by digininja** [comment]
George was going to swap the order of the boolean round to make it more
readable then it is good to go. You can do it yourself in the merge if you
want, I can't modify pull requests but you can.

**Comment by Exhibitioner** [comment]
Sorry for the delay, I've gone and changed the logic around to make it more readable using your suggestion. 

Haven't tested it as no access to the PC for the weekend but feel free to test and merge when happy.

**Comment by digininja** [comment]
Looks good to me, Ryan, if you test it and it runs then I'm happy with it.

**Pull request merged**
