### PR TITLE
Update Readme with link to ansible playbook install method

### PR DESCRIPTION
**Pull request by L1ghtn1ng**
Title says it all.

Side note: github said this file has mixed line endings so has changed it to windows style when I commited this change using the github editor online

### CODE REVIEW

**Comment by digininja** [comment]
Can you add something in there to say that any bugs or questions for this
approach should be sent to you and not us.

You can guarantee that users who have never even heard of ansible will try
this, get stuck, and then start asking us how to fix things.

And check the grammar in your readme, you are missing at least a full stop
in your opening paragraph

**Comment by L1ghtn1ng** [comment]
@digininja I have done your change

**Comment by digininja** [comment]
Seems ok to me but I bet we still get people asking how to use it.

**Comment by L1ghtn1ng** [comment]
Yeah probably, if that happens just ping me and I will have a look
________________________________

**Comment by digininja** [comment]
Up to @ethicalhack3r or @mike-bailey to merge now.

**Comment by ethicalhack3r** [comment]
Thanks for the PR @L1ghtn1ng!

Yea, I'm also not sure if this is going to cause confusion amongst new users. Personally, I like that new users have to go through the process of installing PHP, MySQL, Apache, etc. or at least, are aware of them.

Pointing new users to the Ansible script, may make them less aware of the essential underlying technology stack, and therefore hinder their learning.

Although I think having an Ansible play book is awesome, thank you! I don't think it should be referenced in the readme.

That's my opinion. It would be good to have one more opinion on this from @mike-bailey.

**Comment by L1ghtn1ng** [comment]
I could add on my readme what it installs if that would help at all?
________________________________

**Comment by L1ghtn1ng** [comment]
@ethicalhack3r I have added https://github.com/L1ghtn1ng/dvwa-ansible/commit/2cc0eec00e1a67c4f0538192e8cc5e7b882c0801

**Comment by digininja** [comment]
What he was getting at is more they should go through the process of
setting it all up so they understand what is there and why. Those who have
problems but can be bothered fixing them learn a lot more than sometime
would just running your script.

**Comment by L1ghtn1ng** [comment]
Yeah fair point, both methods have there merits/pro's and con's
________________________________

**Comment by L1ghtn1ng** [comment]
@ethicalhack3r Was just wondering though what the difference to this playbook and docker image this is just another form of that if you think about it but instead of just pulling down docker image you have to setup the OS to then run this playbook against it

**Comment by L1ghtn1ng** [comment]
It would be good to have this added though

**Comment by ethicalhack3r** [comment]
Yea, sorry, I'm still in the same thought as my original comment.

Although, I'm sure your Ansible scripts will be useful to others.

**Comment by ethicalhack3r** [comment]
This could also live somewhere like the wiki - https://github.com/ethicalhack3r/DVWA/wiki

**Comment by ethicalhack3r** [comment]
If the wiki becomes a good source of DVWA usage information, we could eventually link the wiki from the readme, yea

**Pull request closed without merging**
