### PR TITLE
Update URL ReCAPTCHA

### PR DESCRIPTION
**Pull request by Oxicode**

### CODE REVIEW

**Comment by ethicalhack3r** [comment]
Thanks, but I get a 404 for that URL, and the current URL works fine for me.

**Comment by mike-bailey** [comment]
I have the opposite. I get a 404 for the current URL and the new one works for me.

**Comment by digininja** [comment]
I'm with @mike-bailey , the new URL works for me - <https://www.google.com/recaptcha/admin>

**Comment by ethicalhack3r** [comment]
Sorry! My brain mustn't have been fully awake! I thought `create` was the new URL, rather than the old one.

**Pull request merged**
