### PR TITLE
Remove usages of php-mysql

### PR DESCRIPTION
**Pull request by mogria**
I removes the usages of php-mysql so the project also runs on newer PHP versions which don't have php-mysql available.

### CODE REVIEW

**Comment by digininja** [comment]
Wasn't this already done? I thought my PR to do all this had been accepted
already.

**Comment by mogria** [comment]
@digininja 
You mean this one right? Or is there an other one?
https://github.com/RandomStorm/DVWA/pull/63/commits/d185522a990df19485233b1351b8c09fe5b30daf

In some modules not all `mysql_*` calls where replaced (sqli and sqli_blind). This pull request fixes those modules so they work on `5.6.19` on XAMPP as well.

**Comment by digininja** [comment]
Looks like it

**Comment by BinaryResolved** [comment]
Any updates on this?

**Comment by digininja** [comment]
In what way? The pull request was done.

**Comment by BinaryResolved** [comment]
In the way of getting it merged?

**Comment by digininja** [comment]
I'll leave that to @ethicalhack3r to answer, most were done with my PR but there are a few changes left

**Pull request closed without merging**
