### PR TITLE
Displaying mysql connection error details

### PR DESCRIPTION
**Pull request by ssontakke**
For newer versions of MySQL, there is charset error and caching_sha2_password issue. The existing message shown is not indicative. So I am displaying the error no and error string returned by mysqli connection functions.

### CODE REVIEW

**Comment by digininja** [comment]
Looks good to me, my only suggestion is that maybe we should move away from saying "MySQL error" and move to "database error" or something like that as most of our users will be on MariaDB not MySQL.

I had a look and there is on way to know what the server is until after you have connected so we can't probe and then report back pre-login.

**Comment by ssontakke** [comment]
**1st change:** 
Makes sense. I changed that - "MySQL Error #" to "Database Error #". 

**2nd change:**
I also changed this:
Could not connect to the MySQL service.
to 
Could not connect to the database service.

If the 2nd change is not intended, let me know and I will revert that part.

**Comment by digininja** [comment]
Looks good to me.

One other suggested change, the message is in a box which is styled with div.message from /dvwa/css/main.css

That caps the width of the box to 45% so the error is compressed. I think it looks better if the box is the full width of the panel. I was going to suggest just removing the width entry from that style but I don't know where else that style is used so removing something might break other things. So it would be better to add an extra style without the width restriction and apply that to the message box.

Does that make sense? It is a very simple change, but hard to describe.

**Comment by digininja** [comment]
@ethicalhack3r Can you accept this PR, I've got a follow up PR associated with updates to MySQL

**Comment by ethicalhack3r** [comment]
Done, thanks!

**Pull request merged**
