### PR TITLE
CSP Bypass

### PR DESCRIPTION
**Pull request by digininja**
Ready to go. Ideally needs https://github.com/ethicalhack3r/DVWA/pull/255 to be merged and tested first as the changes in there are needed so things don't break when inline scripting is blocked.

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
@digininja can you remove this file .help.php.swp that you have commited please?

**Comment by digininja** [comment]
Bugger, was going to add vim swap files to the git ignore file but forgot.
Will remove it tomorrow.

**Comment by L1ghtn1ng** [comment]
You have done that but you did it probably after already committing the file
________________________________

**Comment by digininja** [comment]
conflict fixed, was just getting the menus in sync. Can't find any swap files so good to go I think.

**Comment by digininja** [comment]
nudge nudge @ethicalhack3r

**Comment by ethicalhack3r** [comment]
Sorry for the delay!

**Comment by digininja** [comment]
Thanks :)

**Pull request merged**
